# Custom Docker Image
#image:
  #file: .gitpod.Dockerfile
# List the start up tasks. 
# Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:  
  - name: Check Setup
    init: |
      python -m pip install --upgrade pip
      # Add commands to Setup Python Environment
    command: |
      clear
      echo "=============="
      echo "    Welcome   "
      echo "=============="
      pyenv versions
      echo ""
# List the ports to expose. 
# Learn more https://www.gitpod.io/docs/config-ports/
ports:
  # jupyter
  - port: 8888
    onOpen: ignore
# Install VSCode Extensions
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
# Install Python 3.7.2
pyenv install -v 3.7.2
# Set Python 3.7.2 as default
pyenv global 3.7.2
# Install all libraries
python -m pip install -r requirements.txt
